version: '3.8'

services:
  yoga-bot:
    build: .
    container_name: yoga-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./images:/app/images:ro
      - ./bot/principles.json:/app/bot/principles.json:ro
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - SENTRY_DSN=${SENTRY_DSN:-}
      - DATA_DIR=/app/data
      - HTTP_PORT=8080
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - yoga-bot-network

networks:
  yoga-bot-network:
    driver: bridge 